#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-XPathEngine
Version  : 0.14
Release  : 21
URL      : https://cpan.metacpan.org/authors/id/M/MI/MIROD/XML-XPathEngine-0.14.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MI/MIROD/XML-XPathEngine-0.14.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libx/libxml-xpathengine-perl/libxml-xpathengine-perl_0.14-1.debian.tar.xz
Summary  : 'a re-usable XPath engine for DOM-like trees'
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-XML-XPathEngine-license = %{version}-%{release}
Requires: perl-XML-XPathEngine-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
XML-XPathEngine
This module is used to add XPath support to XML modules.
INSTALLATION

%package dev
Summary: dev components for the perl-XML-XPathEngine package.
Group: Development
Provides: perl-XML-XPathEngine-devel = %{version}-%{release}
Requires: perl-XML-XPathEngine = %{version}-%{release}

%description dev
dev components for the perl-XML-XPathEngine package.


%package license
Summary: license components for the perl-XML-XPathEngine package.
Group: Default

%description license
license components for the perl-XML-XPathEngine package.


%package perl
Summary: perl components for the perl-XML-XPathEngine package.
Group: Default
Requires: perl-XML-XPathEngine = %{version}-%{release}

%description perl
perl components for the perl-XML-XPathEngine package.


%prep
%setup -q -n XML-XPathEngine-0.14
cd %{_builddir}
tar xf %{_sourcedir}/libxml-xpathengine-perl_0.14-1.debian.tar.xz
cd %{_builddir}/XML-XPathEngine-0.14
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/XML-XPathEngine-0.14/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-XML-XPathEngine
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-XML-XPathEngine/0cc28c6b84235810470600e06e45d061816cd359
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/XML::XPathEngine.3
/usr/share/man/man3/XML::XPathEngine::Boolean.3
/usr/share/man/man3/XML::XPathEngine::Literal.3
/usr/share/man/man3/XML::XPathEngine::NodeSet.3
/usr/share/man/man3/XML::XPathEngine::Number.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-XML-XPathEngine/0cc28c6b84235810470600e06e45d061816cd359

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
