#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-XPathEngine
Version  : 0.14
Release  : 7
URL      : https://cpan.metacpan.org/authors/id/M/MI/MIROD/XML-XPathEngine-0.14.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MI/MIROD/XML-XPathEngine-0.14.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libx/libxml-xpathengine-perl/libxml-xpathengine-perl_0.14-1.debian.tar.xz
Summary  : 'a re-usable XPath engine for DOM-like trees'
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-XML-XPathEngine-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
XML-XPathEngine
This module is used to add XPath support to XML modules.
INSTALLATION

%package dev
Summary: dev components for the perl-XML-XPathEngine package.
Group: Development
Provides: perl-XML-XPathEngine-devel = %{version}-%{release}

%description dev
dev components for the perl-XML-XPathEngine package.


%package license
Summary: license components for the perl-XML-XPathEngine package.
Group: Default

%description license
license components for the perl-XML-XPathEngine package.


%prep
%setup -q -n XML-XPathEngine-0.14
cd ..
%setup -q -T -D -n XML-XPathEngine-0.14 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/XML-XPathEngine-0.14/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-XML-XPathEngine
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-XML-XPathEngine/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Boolean.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Expr.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Function.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Literal.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/LocationPath.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/NodeSet.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Number.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Root.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Step.pm
/usr/lib/perl5/vendor_perl/5.28.1/XML/XPathEngine/Variable.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/XML::XPathEngine.3
/usr/share/man/man3/XML::XPathEngine::Boolean.3
/usr/share/man/man3/XML::XPathEngine::Literal.3
/usr/share/man/man3/XML::XPathEngine::NodeSet.3
/usr/share/man/man3/XML::XPathEngine::Number.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-XML-XPathEngine/deblicense_copyright
